import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SearchData from "@/ContextAPI/searchContext";
import CartData from "@/ContextAPI/cartContext";
import ProductData from "@/ContextAPI/productContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <SearchData>
            <CartData>
              <ProductData>
                {children}
              </ProductData>
            </CartData>
          </SearchData>
        </ClerkProvider>
      </body>
    </html>
  );
}
